[package]
name = "no-op"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
# Abort on panic
panic = "abort"

# Optimize for maximum speed
opt-level = 3

# Enable Link-Time Optimization
lto = "fat"

# Use a single codegen unit
codegen-units = 1
